name: build

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.17', '1.18', '1.19']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup golang v${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: run test
        run: go test ./...

      - name: golangci-lint
        if: matrix.go-version == '1.19'
        uses: golangci/golangci-lint-action@v3
        with:
          skip-cache: true
